name: musicplayerdemo
description: A new Flutter application of music player

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.2

  http: ^0.12.0+2
  rxdart:
  intl: ^0.15.6
  google_fonts:
  audio_manager:
  connectivity: ^3.0.3
  flutter_spinkit: ^4.1.2
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0
  equatable: ^2.0.3

dev_dependencies:
  retrofit_generator: any
  build_runner: any

  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/loading.gif


